opt_in_rules: # some rules are only opt-in
- empty_count
- missing_docs
- vertical_whitespace
# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
- Sources/App
- Sources/Nstack
line_length: 170
trailing_whitespace: false
ignores_empty_lines: true
